FROM centos:7
RUN yum update -y
RUN yum install -y openssh-server
RUN useradd remote_user && \
    echo "1234" | passwd remote_user --stdin && \
    mkdir /home/remote_user/.ssh && \
    chmod 700 /home/remote_user/.ssh
COPY remote-key.pub /home/remote_user/.ssh/authorized_key

RUN chown remote_user:remote_user -R /home/remote_user/.ssh/authorized_key && \
    chmod 600 /home/remote_user/.ssh/authorized_key

RUN /usr/sbin/sshd-keygen

CMD /usr/sbin/sshd -D




==========================================

In order to generate the remote-key, we have to run below commans in the commmand promp.

$ ssh-keygen -f remote-key
then do 'ENTER' two times.

This will generate 2 files:
1. remote-key
2. remote-key.pub
 
